kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-call-webhook
spec:
  podSelector:
    matchLabels:
      app: custom-ca-injector
  ingress:
    - from:
        - namespaceSelector: {}
  policyTypes:
    - Ingress