kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: custom-ca-injector-pki
webhooks:
  - name: custompki.openshift.io
    sideEffects: None
    clientConfig:
      service:
        namespace: custom-ca-injector
        name: custom-ca-injector
        path: /mutate
        port: 443
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTakNDQWpLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVRRd01nWURWUVFEREN0dmNHVnUKYzJocFpuUXRjMlZ5ZG1salpTMXpaWEoyYVc1bkxYTnBaMjVsY2tBeE5UYzROamd5TXpRM01CNFhEVEl3TURNeApNREUwTlRneU5Gb1hEVEl5TURVd09URTBOVGd5TlZvd05qRTBNRElHQTFVRUF3d3JiM0JsYm5Ob2FXWjBMWE5sCmNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVFUzT0RZNE1qTTBOekNDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlpiSUwxT2RJUnNna05pQjFiTjJNNzhiNGNNYUFXZzNoaEZyTmJwVW5teQpUaFhDSHlONDdKOWVtL2VRc1dtam8vNnRqYzBhWW1CcTdYak1zcEc1WEpPMWNSNFdzaWxvZlVaNGFheWM4YW5OCi9DQjVyRmFaaENRVUYwb3Rma3hWeVM1aHR2TE40dWdjb1BwdFBkbkJOS0FGRi8yTlNoUTVVeEUrRkNBeXQrMTUKUjlIdkZmbS8zL3pEUTlJaytoWXhVV051bkF4WEFsbnhIdDJ0a3VnYnNzMWpGWHZveDFqZGdWNzZxd1dsRmJyVApLNUZmTzhLREM2aE05c0lDYW5qZjdjNnIweDFEamRlN0lNR3BVWWU0MVVYNlZFYjlBYlZ5b25RaTNKaTMrYWFHCk5FZGRvU3JnRnpRcHg0TXFVWFp4Q1EyU3B2dnJWd0IyeUs4UzJZUlUzMjBDQXdFQUFhTmpNR0V3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRlBKWUdXdHU0SHE1Qk1IcQp2N1MzbUVhdUJtb1FNQjhHQTFVZEl3UVlNQmFBRlBKWUdXdHU0SHE1Qk1IcXY3UzNtRWF1Qm1vUU1BMEdDU3FHClNJYjNEUUVCQ3dVQUE0SUJBUUJURmRZRnN1TnN2bVNHTzlrWlJBUThnUTEvLzVMZFdWVTVxSFZBSCtSV2hkTXEKSldCZjk1cVRIN0hqdDZkOTNoZGR6eHp2aXJvUUZpM0FxK2JmSStPZHltZ0M1ZTJsZXRtN2VuYTFmUEgvTHh0QQpuOGVXaUZ3MWlaNTY2RFo2dFhObmpWZ09teW5aNFZwYWkxZldBWGRWa1ZQR1lVejFxOWlRVThpay9rNzcyZ0Z0CjZ1YjBWclM3em9pMzdWazh5M3hFMEZSRnBWNk5TeWpFaW4wSzJFbXB4L3BDbDUwRVlkQmZZWWV6MFNwQUFhV2YKWkhaNko1emtIak1tRUxGZEJ4WmhjZTV4UFV5V2FNY3NPT3pZVmdOUmE3QXN6TjhUeEdDbG5sWnlmektrTW1LQgpLNFJuM3Z1S2tlMUQyeEg0dEdVRXc3a3hrbHhaVk8vQVdkVU9hTC80Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVRRd01nWURWUVFEREN0dmNHVnUKYzJocFpuUXRjMlZ5ZG1salpTMXpaWEoyYVc1bkxYTnBaMjVsY2tBeE5UYzROamd5TXpRM01CNFhEVEl3TURFeApNREU0TlRJeU5sb1hEVEl4TURRd09URTBOVGd5TlZvd05qRTBNRElHQTFVRUF3d3JiM0JsYm5Ob2FXWjBMWE5sCmNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVFUzT0RZNE1qTTBOekNDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1hXVy9EN3NRMzR1bjlDNjlYZkxaUzZwZytvSHJJRElEYkxZeU5hTDhpSQpWVnNjNUlybW8wUVJYbmc1ek1GQUFUY3pmOEoxRng2S28xczZZWStDYkt0S2xEOXc3eXFuUE9DRVh2Nnk4Ky96CnJia1JuNDhvN0oxcjcxSmllMEdjck53bm5xTWU5c214aGZ6cXB4Q1FKSFVTTXI0dm54cDNKRUtXeDEvVEZJN2kKd0ZNVlBGNTdkYlo5WmZzdTM3YkVsTzk0OVJqZi9WR1FpTG5UMzVxcjVDZ0ZaVmFWd0xjQjNZNllqTGZQV3cyVwppU0lyNGc2Wm0waFZlTFU2UVFCcHdnY0FaOEk2VmFzRXpzUHpXZi96NmVGQVUvdENQNDVMTTdINW5TaEkzMW54CkJBT3o3aVlnWlVFQnVHTWtPc3VNTHlGRUh6VVJva1hqUUY2WUViWTJ2R01DQXdFQUFhTkVNRUl3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SHdZRFZSMGpCQmd3Rm9BVThsZ1phMjdnZXJrRQp3ZXEvdExlWVJxNEdhaEF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUxuZU14M3l6dklYRC9rcG5iOFlRbGxjCm8zTjdOU1cxYVNvMk9DdHRQWmt1K0wrWnZDaHZpK25uZ0owWFE0SWJtc3BSZGhiMWY3VXRvVjdsSXdsNXNZRG4KQWdqbk0wWUJ0WXkrQnYwR3NPSFdvWjJMaEI4Qm9wSUpZdlpuTjBJUHZQRHZiemt1OEZPUFArTUdjdUIxUEtWdApTbG1BQ0lkdVJIcldFSVlHUG1EV2NtU1JETGp2bjZFaHpEc0R1WmlVcTgvQU5TdlorY3ZheWR0ODVpSVdZU2RYCmNXVGM1TVBYNVp1Y2t3RHV1Z2VwbDZXdlVpTkw5Q1QrN3V3QzBJM1R4VFl3NCthdmQwTm1LUG5HNUdwaFowMTcKT1lkNWdUSGg0RGxoM3JKVGgvOGZMT2hKZjhRLzM0bjBieFJjOHNZODlOM09GTDVwbzRSRTdmVWtONlo2Rjd3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    reinvocationPolicy: Never
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - ''
        apiVersions:
          - v1
        resources:
          - pods
        scope: '*'
    matchPolicy: Exact
    namespaceSelector:
      matchLabels:
        inject: custom-pki
    admissionReviewVersions:
      - v1beta1
    failurePolicy: Ignore
    objectSelector: {}
    timeoutSeconds: 10
