kind: Deployment
apiVersion: apps/v1
metadata:
  name: quarkus-hello-no-inject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quarkus-hello-no-inject
  template:
    metadata:
      labels:
        app: quarkus-hello-no-inject
    spec:
      containers:
        - name: quarkus-hello
          image: 'quay.io/radudd/quarkus-hello:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
  strategy:
    type: RollingUpdate
