kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-spring
  template:
    metadata:
      labels:
        app: hello-spring
      annotations:
        custompki.openshift.io/inject-jks: 'true'
    spec:
      containers:
        - name: hello-spring
          image: 'quay.io/radudd/hello-spring:latest'
          command:
            - sh
            - '-c'
            - >-
              java
              -Djavax.net.ssl.trustStore=/etc/pki/ca-trust/extracted/java/cacerts
              -Djavax.net.ssl.trustStorePassword=changeit
              -jar /app.jar
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: /config/
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: hello-spring-config
